version: '3'

services:
  monitor-admin:
    image: monitor-admin:4.8.0
    container_name: monitor-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /home/ubuntu/apps/monitor/logs/:/ruoyi/monitor/logs
    privileged: true
    network_mode: "host"
    restart: always
