version: '3'

services:
  xxl-job-admin:
    image: xxl-job-admin:4.8.0
    container_name: xxl-job-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /home/ubuntu/apps/xxljob/logs/:/ruoyi/xxljob/logs
    privileged: true
    network_mode: "host"
    restart: always
